# See the documentation for more information:
# https://packit.dev/docs/configuration/
actions:
  changelog-entry:
    - bash -c 'echo "- New upstream release"'
  post-upstream-clone:
    - wget https://src.fedoraproject.org/rpms/rust-ignition-config/raw/rawhide/f/rust-ignition-config.spec
  prepare-files:
    - bash -c 'rust2rpm -s ignition-config $PACKIT_PROJECT_VERSION'

specfile_path: rust-ignition-config.spec
downstream_package_name: rust-ignition-config
upstream_package_name: ignition-config-rs
upstream_tag_template: v{version}
# add or remove files that should be synced
files_to_sync:
  - rust-ignition-config.spec
  - .packit.yaml

jobs:

- job: propose_downstream
  trigger: release
  # https://packit.dev/docs/configuration#aliases
  dist_git_branches:
    - fedora-rawhide

- job: koji_build
  trigger: commit
  dist_git_branches:
    - fedora-all

- job: bodhi_update
  trigger: commit
  dist_git_branches:
    - fedora-all
